# 워크플로우의 이름
name: Deploy to AWS EC2 (Self-Hosted)

# 어떤 이벤트가 발생했을 때 이 워크플로우를 실행할지 정의
on:
  push:
    branches:
      - main  # main 브랜치에 push가 발생했을 때만 실행

# 실행될 작업(Job)들을 정의
jobs:
  deploy:
    # 이 작업이 실행될 가상 환경의 종류
    runs-on: self-hosted

    # 작업의 단계(Step)들을 정의
    steps:
      # 1. 코드를 체크아웃하는 단계
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 배포 스크립트를 직접 실행
      - name: Deploy Application
        run: ./deploy_v2.sh