# .github/workflows/deploy.yml

name: Build and Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # 모든 작업을 self-hosted runner에서 실행
    runs-on: self-hosted

    steps:
      # 1. 코드를 체크아웃합니다.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. .env 파일을 생성합니다.
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # 3. Docker Hub에 로그인합니다.
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKKERHUB_USERNAME }} # 오타 수정: DOCKERHUB_USERNAME
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. 이미지를 빌드하고 Docker Hub에 푸시합니다.
      - name: Build and push Docker images
        run: |
          sudo docker-compose -f docker-compose.build.yml build
          sudo docker-compose -f docker-compose.build.yml push

      # 5. 최신 이미지를 받아와서 서비스를 재시작합니다.
      - name: Pull latest images and restart services
        run: |
          sudo docker-compose pull
          sudo docker-compose up -d --remove-orphans
          sudo docker image prune -f